---
- name: update apt cache
  apt:
      update_cache: yes

- name: Ensure nginx is installed.
  apt:
    name: "{{ nginx_package_name }}"
    state: present
    default_release: "{{ nginx_default_release }}"
  register: nginx_res
  until: nginx_res is succeeded
  retries: 20
  delay: 30