- hosts: localhost
  connection: local
  vars:
    - webhook: https://automation.atlassian.com/pro/hooks/89f8e0478bbe2af3aac618b5654c6acdd15d8e70
    - delete: "no"
  tasks:
    - block:
        - set_fact:
            root_email: "{{ email.split('@')[0] }}+{{ ansible_date_time.epoch | to_uuid | split('-') | first | join('')}}@{{ email.split('@')[1]}}"
            unique_name: "{{ first_name }}-{{ last_name }}-{{ ansible_date_time.epoch | to_uuid | split('-') | first | join('')}}"
        - name: Create aws-account
          include_role:
            name: aws-account
          when: delete == 'no'
        - name: Delete aws-account
          include_role:
            name: aws-account
            tasks_from: delete_aws
          when: delete == 'yes'
        - name: Return webhook
          include_role:
            name: aws-account
            tasks_from: return_webhook
          when: delete == 'no'
      rescue:
        - name: Delete directory
          ansible.builtin.file:
            path: "{{ansible_facts.user_dir}}/{{ root_email }}"
            state: absent
        - name: Return error webhook
          include_role:
            name: aws-account
            tasks_from: error_return_webhook
