- hosts: localhost
  connection: local 
  tasks:
    - block:
        - name: Create aws-account
          include_role:
            name: aws-account
        - name: Return webhook
          include_role:
            name: aws-account
            tasks_from: return_webhook
      rescue:
        - name: Return error webhook
          include_role:
            name: aws-account
            tasks_from: error_return_webhook