- hosts: localhost
  connection: local
  vars:
    - webhook: https://automation.atlassian.com/pro/hooks/95e9eb4c9992956d86e622abcece07ded2648191
  tasks:
    - block:
        - name: Create aws-account
          include_role:
            name: aws-account
          when: delete == 'no'
        - name: Delete aws-account
          include_role:
            name: aws-account
            tasks_from: delete_aws
          when: delete == 'yes'
        - name: Return webhook
          include_role:
            name: aws-account
            tasks_from: return_webhook
      rescue:
        - name: Return error webhook
          include_role:
            name: aws-account
            tasks_from: error_return_webhook