- name: Register domain
  hosts: localhost
  tasks:
    - block: 
        - name: Register domain role
          include_role:
            name: nginx-proxy
        - name: Return webhook
          include_role:
            name: nginx-proxy
            tasks_from: return_webhook
      rescue:
        - name: Return webhook
          include_role:
            name: nginx-proxy
            tasks_from: error_return_webhook 


