- name: Example playbook
  hosts: localhost
  vars:
    domains:
      - domain_names: "aandd.io"
        cert_id: 77
      - domain_names: "agileops.dev"
        cert_id: 58
  tasks:
    - name: Retrieve ssl_id based on domain name
      set_fact:
        ssl_id: "{{ item.cert_id }}"
      loop: "{{ domains }}"
      when: item.domain_names in register_domain

