- name: Example playbook
  hosts: localhost
  vars:
    files_to_download:
      - "https://product-downloads.atlassian.com/software/confluence/downloads/atlassian-confluence-8.0.4-x64.bin"
      - "https://product-downloads.atlassian.com/software/confluence/downloads/atlassian-confluence-8.0.5-x64.bin"
      - "https://product-downloads.atlassian.com/software/confluence/downloads/atlassian-confluence-8.0.6-x64.bin"
  tasks:
    - name: Get list of filenames from URLs
      set_fact:
        filenames: "{{ files_to_download | map('basename') | list }}"
    - debug:
        var: filenames