- name: Example playbook
  hosts: localhost
  vars:
    email: "tinhtq@agileops.vn"
  tasks:
    - set_fact:
          mysql_version: "{{ applications | select('search','mysql') | map('split', ':') | map(attribute=1) | first | default('')}}"
          postgresql_version: "{{ applications | select('search','postgresql') | map('split', ':') | map(attribute=1) | first | default('')}}"
    - name: Print values
      debug:
        msg: "{{mysql_version}}, {{ postgresql_version }}"
