- name: Example playbook
  hosts: localhost
  vars:
    email: "tinhtq@agileops.vn"
  tasks:
    - name: Print values
      debug:
        msg: "{{ email.split('@')[0] }}+{{ ansible_date_time.epoch | to_uuid | split('-') | first | join('')}}@{{ email.split('@')[1]}}"
