- name: Example playbook
  hosts: localhost
  tasks:
    - name: Copy main.tf file
      vars:
        root_email: "tinhtq"
      template:
        src: ./roles/aws-account/templates/Makefile.j2
        dest: "/Users/tinhtq/Documents/Projects/ansible-playbook/ansible_automation/test/Makefile"
