- name: Example playbook
  hosts: localhost
  vars:
    names:
      - domain_names: "aandd.io"
        cert_id: 77
      - domain_names: "agileops.dev"
        cert_id: 58
  tasks:
    - name: Retrieve ssl_id based on domain name
      set_fact:
        ssl2_id: "{{ item.ssl_id }}"
      loop: "{{ names }}"
      when: item.domain_names in register_domain
      vars:
        register_domain: "agileops.dev"
