
- name: Send to webhook
  uri:
    url: "{{webhook}}?issue={{ issueKey }}"
    method: POST
    body: "{{ lookup('template', './error_webhook_body.json.j2') }}"
    body_format: json
    validate_certs: no
    headers:
      Authorization: "{{ basic_auth }}"
