- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: "{{ansible_facts.user_dir}}/{{ root_email }}"
    state: directory
    mode: "0755"
- name: Copy template file
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - {
        src: main.tf.j2,
        dest: "{{ansible_facts.user_dir}}/{{ root_email }}/main.tf",
      }

- name: Terraform init
  command: terraform init -backend-config="region=ap-southeast-1" -backend-config="bucket=tf-states-ap-southeast-1-368886022624" -backend-config="dynamodb_table=tf-states-ap-southeast-1-368886022624" -backend-config="key={{ root_email }}/terraform.tfstate"
  args:
    chdir: "{{ansible_facts.user_dir}}/{{ root_email }}"

- name: Terraform destroy
  command: terraform destroy -auto-approve
  args:
    chdir: "{{ansible_facts.user_dir}}/{{ root_email }}"

- name: Delete directory
  ansible.builtin.file:
    path: "{{ansible_facts.user_dir}}/{{ root_email }}"
    state: absent

- name: Send to deleted webhook
  uri:
    url: "{{ delete_webhook }}"
    method: POST
    body: "{{ lookup('template', './delete-webhook.json.j2') }}"
    body_format: json
    headers:
      Authorization: "{{ basic_auth }}"
