---
- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: "{{ansible_facts.user_dir}}/{{ ansible_date_time.epoch | to_uuid | split('-') | first | join('')}}"
    state: directory
    mode: '0755'

- name: Copy main.tf file
  template:
    src: main.tf.j2
    dest: "{{ansible_facts.user_dir}}/{{ ansible_date_time.epoch | to_uuid | split('-') | first | join('')}}/main.tf"

- name: Terraform init
  command: terraform init
  become: true
  args:
    chdir: "{{ansible_facts.user_dir}}/{{ ansible_date_time.epoch | to_uuid | split('-') | first | join('')}}"


- name: Terraform apply
  command: terraform apply -auto-approve
  become: true
  args:
    chdir: "{{ansible_facts.user_dir}}/{{ ansible_date_time.epoch | to_uuid | split('-') | first | join('')}}"


