---
- set_fact:
    root_email: "{{ email.split('@')[0] }}+{{ ansible_date_time.epoch | to_uuid | split('-') | first | join('')}}@{{ email.split('@')[1]}}"

- name: Configure AWS.
  shell: aws configure set {{ item.key }} {{ item.value }} --profile {{ aws_profile }}
  with_dict:
    aws_access_key_id: "{{ aws_access_key }}"
    aws_secret_access_key: "{{ aws_secret_key }}"
    region: "{{ aws_region }}"
    format: "{{ aws_format }}"
  changed_when: false

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: "{{ansible_facts.user_dir}}/{{ root_email }}"
    state: directory
    mode: '0755'

- name: Copy template file
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items: 
    - {src: main.tf.j2, dest: "{{ansible_facts.user_dir}}/{{ root_email }}/main.tf"}
    - {src: Makefile.j2, dest: "{{ansible_facts.user_dir}}/{{ root_email }}/Makefile"}


- name: Terraform init
  command: terraform init
  args:
    chdir: "{{ansible_facts.user_dir}}/{{ root_email }}"


- name: Terraform apply
  command: terraform apply -auto-approve
  args:
    chdir: "{{ansible_facts.user_dir}}/{{ root_email }}"

- name: Delete directory
  ansible.builtin.file:
    path: "{{ansible_facts.user_dir}}/{{ root_email }}"
    state: absent
