- name: Ensure MySQL databases are present.
  mysql_db:
    name: "{{ jsw_database_name  }}"
    collation: utf8_general_ci
    encoding: utf8
    state: present

- name: Download MySQL Connector/J
  command: "wget https://dev.mysql.com/get/Downloads/Connector-J/mysql-connector-j-8.0.32.tar.gz -O {{ ansible_env.PWD }}/mysql-connector-j-8.0.32.tar.gz"
 

- name: Extract MySQL Connector/J
  unarchive:
    src: "{{ ansible_env.PWD }}/mysql-connector-j-8.0.32.tar.gz"
    dest: "{{ ansible_env.PWD }}"
    copy: no


- name: Move MySQL Connector/J JAR to /opt/
  command: "mv {{ ansible_env.PWD }}/mysql-connector-j-8.0.32/mysql-connector-java-8.0.32.jar {{ jsw_installation_dir }}/lib"

- name: Set owner of MySQL Connector/J JAR
  file:
    path: "{{ jsw_installation_dir }}/lib/mysql-connector-java-8.0.32.jar"
    owner: "jira"
    group: "jira"