- debug:
    var: ansible_facts
- name: Copy file power to folder
  template:
    src: "error-curl-command.ps1.j2"
    dest: "{{ ansible_user_dir }}/error-curl-command.ps1"
    owner: "{{ ansible_ssh_user }}"

- name: Run command
  win_shell: |
    Powershell.exe Set-ExecutionPolicy RemoteSigned
    Powershell.exe -File {{ ansible_user_dir }}/curl-command.ps1
    Powershell.exe Set-ExecutionPolicy Restricted
    del {{ ansible_user_dir }}/curl-command.ps1

    