---
- name: Check if file exists
  stat:
    path: "{{ ansible_env.PWD }}/minio-binaries/mc"
  register: file_info

- name: Install minio client
  shell: |
    curl https://dl.min.io/client/mc/release/linux-amd64/mc --create-dirs -o {{ ansible_env.PWD }}/minio-binaries/mc
    chmod +x {{ ansible_env.PWD }}/minio-binaries/mc
    {{ ansible_env.PWD }}/minio-binaries/mc alias set minio http://storage.agileops.int {{ key }} {{ value }}
  when: not file_info.stat.exists

# - name: Download deb package for postgresql
#   shell: wget -P {{ ansible_env.PWD }} {{ item }}
#   with_items: '{{ deb_file_download }}'

- name: Copy package from minio server
  register: postgresql_package
  until: postgresql_package is succeeded
  retries: 5
  delay: 15
  shell: "{{ ansible_env.PWD }}/minio-binaries/mc cp minio/agileops/database/postgresql-{{postgresql_version}}/ {{ ansible_env.PWD }}/ --recursive"


- name: Select note
  shell: echo "postgresql-common postgresql-common/obsolete-major select Ok" | sudo debconf-set-selections;
  become: true
  register: note_result
  until: note_result is succeeded
  retries: 10
  delay: 30

- name: Install postgresql
  become: true
  shell: dpkg -i {{ ansible_env.PWD }}/*.deb
  ignore_errors: true
  environment:
    DEBIAN_FRONTEND: noninteractive
  register: dpkg_result
  until: '"dpkg: error: dpkg frontend lock is locked by another process" not in dpkg_result.stderr'
  retries: 10
  delay: 45

- name: Fix broken
  shell: apt --fix-broken install -y
  become: true
  notify: restart postgresql

- name: Remove deb file
  shell: rm -rf {{ ansible_env.PWD }}/*.deb

